#!/bin/bash -e

NGINX_DIR=`pwd`/nginx_temp
NGINX_CONF=${NGINX_DIR}/conf/nginx.conf

export PATH=$PATH:/usr/local/openresty/nginx/sbin
mkdir -p ${NGINX_DIR}/{logs,conf}

if [ ! -h ${NGINX_CONF} ]; then
	ln -s ../../nginx.conf ${NGINX_CONF}
fi

if [ ! -h ${NGINX_DIR}/lib ]; then
	ln -s ../../lib ${NGINX_DIR}
fi

nginx -p ${NGINX_DIR}
